//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_DISH
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BOOK_DISH()
        {
            this.COOKING_STAGES = new HashSet<COOKING_STAGES>();
            this.RECIPEs = new HashSet<RECIPE>();
        }
    
        public int C_id_dish { get; set; }
        public string name_dish { get; set; }
        public int time_pr { get; set; }
        public int C_id_cuisine_national { get; set; }
        public int C_id_cooking_method { get; set; }
        public int C_id_type_dish { get; set; }
        public int C_id_cuisine_type { get; set; }
        public string calories { get; set; }
        public byte[] imageData { get; set; }
    
        public virtual COOKING_METHOD COOKING_METHOD { get; set; }
        public virtual CUISINE_NATIONAL CUISINE_NATIONAL { get; set; }
        public virtual CUISINE_TYPE CUISINE_TYPE { get; set; }
        public virtual TYPE_DISH TYPE_DISH { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COOKING_STAGES> COOKING_STAGES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECIPE> RECIPEs { get; set; }
    }
}
