//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CookHelperEntities : DbContext
    {
        public CookHelperEntities()
            : base("name=CookHelperEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BOOK_DISH> BOOK_DISH { get; set; }
        public virtual DbSet<COOKING_METHOD> COOKING_METHOD { get; set; }
        public virtual DbSet<COOKING_STAGES> COOKING_STAGES { get; set; }
        public virtual DbSet<CUISINE_NATIONAL> CUISINE_NATIONAL { get; set; }
        public virtual DbSet<CUISINE_TYPE> CUISINE_TYPE { get; set; }
        public virtual DbSet<INGREDIENT> INGREDIENTs { get; set; }
        public virtual DbSet<RECIPE> RECIPEs { get; set; }
        public virtual DbSet<TYPE_DISH> TYPE_DISH { get; set; }
        public virtual DbSet<UNIT_MEASURE> UNIT_MEASURE { get; set; }
    }
}
